---
version: '3'
services:
  ubuntu:
    container_name: ubuntu
    build:
      context: ./modules/docker
      dockerfile: Dockerfile
    image: dceoy/ubuntu:latest
    entrypoint:
      - tail
    command:
      - -F
      - /dev/null
